-- Seed Dictionary Data from CSVs

-- Function to clean and parse array string like "[""a"",""b""]" to text[]
CREATE OR REPLACE FUNCTION parse_csv_array(input_text TEXT)
RETURNS TEXT[] AS $$
DECLARE
    cleaned_text TEXT;
BEGIN
    -- Remove outer brackets and quotes if present
    cleaned_text := TRIM(BOTH '[]"' FROM input_text);
    -- Replace double quotes with nothing inside the string if needed, or handle CSV escaping
    -- Simple split by comma and quote handling
    RETURN string_to_array(cleaned_text, '","');
END;
$$ LANGUAGE plpgsql;

-- Insert Processes (from job_dictionary_rows.csv)
INSERT INTO public.dictionary_processes (id, name, keywords)
VALUES 
('0651961d-1b10-4b00-9cfe-aa2ff85f5b63', 'Legal y Cumplimiento', ARRAY['legal','compliance','cumplimiento normativo','regulaciones','gdpr','proteccion de datos','contratos','propiedad intelectual','auditoria legal','risk management','gestion de riesgos','politicas corporativas','etica empresarial','due diligence','director de legales','contract management']),
('07f551bf-d226-480d-82d8-b0f9c02fb2c2', 'Experiencia del Cliente', ARRAY['Customer Experience','CX','Experiencia del Cliente','Customer Success','Customer Support','Atención al Cliente','Service Desk','Help Desk','Soporte Técnico','Customer Journey','NPS','CSAT','Customer Feedback','Gestión de Reclamos','Retención de Clientes']),
('0bac5f11-e50c-47d2-a61d-653741239a7a', 'Finanzas y Contabilidad', ARRAY['finanzas','contabilidad','cfo','chief financial officer','controller','contador','analisis financiero','presupuestos','forecasting','reporting financiero','auditoria','tesoreria','cuentas por pagar','cuentas por cobrar','conciliacion bancaria','impuestos','gaap','ifrs','erp financiero','financiero','director financiero']),
('2283a841-16d0-4394-accf-ce5f1f29f1bc', 'Liderazgo IT', ARRAY['CIO','Chief Information Officer','Director de Tecnología','Director de Sistemas','Gerente de IT','IT Manager','Tecnología de la Información','Estrategia Tecnológica','Transformación Digital','Innovación Tecnológica','Gestión de TI','Arquitectura Empresarial','Gobierno de TI','Planificación Estratégica de TI','versionado_test_final']),
('27d4c493-3fc6-4cf6-86c0-cb156d79fafd', 'DevOps y Desarrollo', ARRAY['devops','software development','ci/cd','continuous integration','continuous deployment','infrastructure as code','containerizacion','docker','kubernetes','microservicios','api development','frontend','git','jenkins','gitlab']),
('44711b90-4d48-49b7-9bee-412bf8deda99', 'Business Intelligence y Análisis', ARRAY['bi','business intelligence','analisis de datos','data analytics','reporting','dashboards','kpis','metricas','data visualization','data warehouse','etl','data mining','analisis predictivo','big data','datawarehouse','ingeniero de datos','inteligencia de datos','explotacion de datos','gestion de datos']),
('4708be45-b760-4e90-a93a-13f54ec18137', 'Calidad y Procesos', ARRAY['Calidad','Quality Assurance','QA','Gestión de Calidad','Mejora Continua','Lean','Six Sigma','BPM','Business Process Management','Optimización de Procesos','ISO 9001','Auditoría de Calidad','Control de Calidad','Testing','QC','Gestion de procesos']),
('59965ca9-52e6-45a6-933e-63560203ff76', 'Comercio Electrónico', ARRAY['e-commerce','comercio electronico','tienda online','marketplace','gestion de catalogo','carrito de compras','pasarelas de pago','fulfillment','logistica e-commerce','omnicanalidad','checkout','inventario online','shopify','woocommerce','tiendanube']),
('67e962a8-151f-4741-9359-018ed86b00db', 'Innovación Tecnológica', ARRAY['Innovación','Innovation','I+D','Research and Development','Nuevas Tecnologías','Emerging Technologies','AI','Artificial Intelligence','Machine Learning','IoT','Internet of Things','Blockchain','AR/VR','Realidad Aumentada','Realidad Virtual']),
('701db1ae-35f0-4aa4-a9ad-f61053ef19dc', 'Inversiones y gestión de cartera', ARRAY['tesoreria','mesa de dinero','portfolio manager','rofex','byma','inversiones','custodia','mercado de capitales','trading, titulos y cambios','portfolio']),
('70920edf-a09a-4075-8ae5-20a3fa368fe9', 'Transformación Digital', ARRAY['Transformación Digital','Digital Transformation','Innovación','Digitalización','Automatización de Procesos','RPA','Robotic Process Automation','Change Management','Gestión del Cambio','Adopción Digital','Modernización','Cloud Adoption','Digital Strategy']),
('7cf5a875-1d03-4987-ab19-513008a6beae', 'Marketing y Ventas', ARRAY['Marketing','Ventas','Sales','Marketing Digital','CRM','Customer Relationship Management','Lead Generation','Email Marketing','Social Media','Content Marketing','SEO','SEM','Publicidad Digital','Analytics','Marketing Automation','Gestión de Campañas','Branding']),
('9769c1d5-7b42-406e-8bbd-668ed4bd1df1', 'Soporte y Atención al Cliente', ARRAY['soporte','support','help desk','service desk','customer support','technical support','soporte tecnico','ticketing','itil','incident management','problem management','service level agreement','sla','first level support','second level support']),
('9b44786c-abaf-46ed-a363-0bbfb1e221ed', 'Gestión de Proyectos', ARRAY['pmo','project management office','gestion de proyectos','project manager','scrum master','agile coach','metodologias agiles','planificacion de proyectos','gestion de portafolio','gestion de programas','gestion de riesgos','gestion de cambios','gestion de stakeholders','gestion de recursos','gestion de cronogramas','program manager','coordinador de proyectos','administrador de proyectos','gestor de cambios']),
('a5ccef16-fd56-422c-8130-6d74e7d73c92', 'Recursos Humanos', ARRAY['RRHH','Human Resources','Recursos Humanos','Gestión de Talento','Reclutamiento','Selección','Onboarding','Capacitación','Desarrollo Organizacional','Compensaciones','Beneficios','Nómina','Evaluación de Desempeño','Clima Laboral','Cultura Organizacional','Employee Experience']),
('c6a92727-dbd9-4d3e-a50c-e83f5ecc4f52', 'Infraestructura y Bases de Datos', ARRAY['infraestructura','dba','database administrator','administrador de bases de datos','arquitectura de infraestructura','gestion de servidores','redes','virtualizacion','cloud infrastructure','on-premise','hybrid cloud','disaster recovery','alta disponibilidad','performance tuning','data modeling','sysadmin','infrastructure administrator','server administrator','networking','server lead','vmware','hyper-v','citrix','it administrator']),
('c9b347a7-f0e6-42bb-9d72-f5201abd46e2', 'Logística y Operaciones', ARRAY['logistica','operaciones','supply chain','cadena de suministro','gestion de almacenes','warehouse management','picking','packing','control de inventarios','transporte','distribucion','last mile','planificacion de demanda','procurement','compras','gestion de proveedores','comex','importaciones']),
('ff3be60f-e23d-402e-a975-bb5d92c74447', 'Seguridad IT', ARRAY['cybersecurity','information security','ciso','chief information security officer','soc','security operations center','gestion de vulnerabilidades','pentesting','ethical hacking','firewall','ids/ips','siem','gestion de identidades','iam','compliance','iso 27001','nist','seguridad de redes','seguridad de aplicaciones','seguridad informatica'])
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    keywords = EXCLUDED.keywords;

-- Insert Vendors and Products (from tech_dictionary_rows.csv)
-- First, insert unique vendors
INSERT INTO public.dictionary_vendors (name)
SELECT DISTINCT category FROM (
    VALUES 
    ('Google'), ('Zoho '), ('Tableau'), ('MicroStrategy'), ('Oracle'), ('Atlassian'), ('Microsoft'), ('SAP'), ('HubSpot'), ('Salesforce'), ('Workday'), ('Qlik'), ('Amazon'), ('ServiceNow')
) AS v(category)
ON CONFLICT DO NOTHING;

-- Then insert products, linking to vendors
-- Note: We use a DO block to handle the UUID lookups for vendors
DO $$
DECLARE
    v_google_id UUID;
    v_zoho_id UUID;
    v_tableau_id UUID;
    v_microstrategy_id UUID;
    v_oracle_id UUID;
    v_atlassian_id UUID;
    v_microsoft_id UUID;
    v_sap_id UUID;
    v_hubspot_id UUID;
    v_salesforce_id UUID;
    v_workday_id UUID;
    v_qlik_id UUID;
    v_amazon_id UUID;
    v_servicenow_id UUID;
BEGIN
    -- Get Vendor IDs
    SELECT id INTO v_google_id FROM public.dictionary_vendors WHERE name = 'Google';
    SELECT id INTO v_zoho_id FROM public.dictionary_vendors WHERE name = 'Zoho ';
    SELECT id INTO v_tableau_id FROM public.dictionary_vendors WHERE name = 'Tableau';
    SELECT id INTO v_microstrategy_id FROM public.dictionary_vendors WHERE name = 'MicroStrategy';
    SELECT id INTO v_oracle_id FROM public.dictionary_vendors WHERE name = 'Oracle';
    SELECT id INTO v_atlassian_id FROM public.dictionary_vendors WHERE name = 'Atlassian';
    SELECT id INTO v_microsoft_id FROM public.dictionary_vendors WHERE name = 'Microsoft';
    SELECT id INTO v_sap_id FROM public.dictionary_vendors WHERE name = 'SAP';
    SELECT id INTO v_hubspot_id FROM public.dictionary_vendors WHERE name = 'HubSpot';
    SELECT id INTO v_salesforce_id FROM public.dictionary_vendors WHERE name = 'Salesforce';
    SELECT id INTO v_workday_id FROM public.dictionary_vendors WHERE name = 'Workday';
    SELECT id INTO v_qlik_id FROM public.dictionary_vendors WHERE name = 'Qlik';
    SELECT id INTO v_amazon_id FROM public.dictionary_vendors WHERE name = 'Amazon';
    SELECT id INTO v_servicenow_id FROM public.dictionary_vendors WHERE name = 'ServiceNow';

    -- Insert Products
    INSERT INTO public.dictionary_products (id, vendor_id, name, keywords)
    VALUES
    ('047628f8-45fb-4276-b8f3-31ecce320fba', v_google_id, 'Google Looker', ARRAY['Looker','Google Looker','Looker Studio','Looker Studio Pro','Looker BI','Looker Analytics','Looker Cloud','Looker Data Platform','Looker Developer','LookML','LookML Developer','LookML Model','LookML View','Looker API','Looker REST API','Looker SDK','OAuth Looker','Looker Actions']),
    ('081827c5-178f-4f47-b42d-473f93f1118b', v_zoho_id, 'Zoho CRM', ARRAY['ZOHO CRM','ZOHO','bigin','crm plus','zoho desk','zoho mail']),
    ('1069a41d-ee2a-4efd-ba6c-c5c77fb23cd2', v_tableau_id, 'Tableau Desktop y Server', ARRAY['Tableau','Tableau Desktop','Tableau Server','Tableau Online','Tableau Cloud','Tableau Public','Tableau Prep','Tableau Prep Builder','Tableau Bridge','Tableau Mobile','Tableau Reader','Tableau Workbook','Tableau Dashboard','Tableau Extract Refresh','Tableau Bridge Connection','Tableau Prep Flow']),
    ('10b58311-7b2f-4493-9f95-c6b768ea3a27', v_microstrategy_id, 'MicroStrategy', ARRAY['MSTR','Microstrategy','Strategy One','MicroStrategy','MicroStrategy Analytics','MicroStrategy Platform','MicroStrategy BI','MicroStrategy Cloud','MicroStrategy Enterprise Analytics','MicroStrategy Web','MicroStrategy Desktop','MicroStrategy Developer','MicroStrategy Workstation','MicroStrategy Library','MicroStrategy Mobile','MicroStrategy Dossier','MicroStrategy Intelligence Server','MicroStrategy Command Manager','MicroStrategy Distribution Services','MicroStrategy Project','MicroStrategy Administrator','Dossiers','MicroStrategy SDK','MicroStrategy REST API','MicroStrategy Library API','MicroStrategy Mobile SDK','MicroStrategy Library Mobile']),
    ('156f5ec7-c99f-4166-8d47-d21125a9ea17', v_oracle_id, 'Oracle NetSuite', ARRAY['NetSuite']),
    ('17c38560-9c0e-4739-bfa9-787ee283312e', v_atlassian_id, 'Jira', ARRAY['Jira Software','Jira Service Management','Jira','Atlassian','Atlassian Jira','Jira Cloud','Jira Server','Jira Data Center','Jira On-Premise','Jira Admin','Jira Administrator','Jira API','Jira REST API','Jira Cloud API','Jira Server API','Webhooks','Atlassian Connect','Atlassian Marketplace','Jira App','Jira Add-on','Jira Plugin','ScriptRunner','JMWE','Automation for Jira','Jira Automation','Bitbucket','Bamboo','Trello','Jira Align','Atlassian Access','Atlassian Cloud','Atlassian Admin Hub','Atlassian Identity Manager','Atlassian Analytics','Insight Asset Management','Tempo Timesheets','Zephyr','Xray Test Management','Confluense','Confluence']),
    ('180af780-5354-46fc-8c0e-690f298e2069', v_microsoft_id, 'Azure', ARRAY['Microsoft Azure','Azure Cloud','Entra ID','Azure Portal','Azure Resource Manager','ARM Templates','Azure CLI','PowerShell Azure','Azure Subscription','Azure Tenant','Azure Regions','Azure Availability Zones','Azure Virtual Network','Azure Load Balancer','Azure Application Gateway','Azure DNS','Azure Traffic Manager','Azure Firewall','Azure Bastion','Azure ExpressRoute','Azure VPN Gateway','Azure Virtual Machines','Azure VM Scale Sets','Azure Disks','Azure Storage Account','Azure Blob Storage','Azure Files','Azure Queue Storage','Azure Table Storage','Azure Managed Disks','Azure Backup','Azure Site Recovery','Azure SQL Database','Azure Cosmos DB','Azure Database for MySQL','Azure Database for PostgreSQL','Azure Data Lake','Azure Synapse Analytics','Azure Data Factory','Azure Active Directory','AAD','Azure AD B2C','Azure AD Domain Services','Managed Identity','Role-Based Access Control','RBAC','Azure Key Vault','Azure Policy','Azure Defender','Microsoft Defender for Cloud','Azure Sentinel','Azure Security Center','Azure Privileged Identity Management','Conditional Access','Visual Studio','Visual Studio Code','Azure SDK','Azure REST API','PowerShell Az Module','Azure ARM Templates','Bicep','Terraform Azure','Pulumi Azure']),
    ('3719819c-0f95-4541-b280-5c476430bf7d', v_sap_id, 'SAP SuccessFactors', ARRAY['SuccessFactors','SAP SF','SAP SuccessFactors','SAP HXM','Human Experience Management','SAP SuccessFactors HXM Suite','Employee Central','EC','Employee Central Payroll','ECP','Recruiting Management','RCM','Recruiting Marketing','RMK','Onboarding','Onboarding 2.0','Learning Management System','Performance and Goals','PMGM','Compensation','Succession and Development','SAP SuccessFactors Integration Center','Intelligent Services','Business Rules','Metadata Framework','Role-Based Permissions','SAP SuccessFactors API','OData API','SFAPI','SuccessFactors Report Canvas','People Analytics','Workforce Analytics','Integration with SAP ERP','Integration with SAP HCM','SAP Cloud Platform Integration','SAP Identity Authentication','SAP SuccessFactors Consultant','SAP SuccessFactors Functional Consultant','SAP SuccessFactors Technical Consultant']),
    ('387876e3-f8f5-4ffa-9b33-643e5e8435f0', v_hubspot_id, 'HubSpot CRM & Marketing Hub', ARRAY['HubSpot','HubSpot CRM','HubSpot Platform','HubSpot Cloud','HubSpot SaaS','HubSpot Admin','HubSpot Portal','HubSpot Sales','HubSpot Marketing','HubSpot Service','HubSpot Operations','HubSpot CMS','HubSpot Free CRM','HubSpot Enterprise','HubSpot Starter','HubSpot Professional','HubSpot API','HubSpot REST API','HubSpot Webhooks','HubSpot Custom Integration','HubSpot App Marketplace','HubSpot Data Sync','HubSpot Operations Hub','Salesforce Integration','HubSpot for Gmail','HubSpot for Outlook','HubSpot Integration with LinkedIn','HubSpot API Key','HubSpot Private App','OAuth HubSpot','HubL','HubSpot CMS Hub','HubSpot Theme','HubSpot Templates','HubSpot Modules','HubSpot SDK']),
    ('3db9533f-0ce9-418d-aad2-f8e822ac6cce', v_sap_id, 'SAP S/4HANA', ARRAY['S/4HANA','S4HANA','SAP HANA','SAP S4HANA','SAP S/4HANA','HANA Database','SAP HANA Studio','SAP HANA Modeling','SAP HANA SQLScript','SAP HANA XS','SAP Fiori','SAP Fiori Launchpad','SAP UI5','SAP S/4HANA Finance','SAP S/4HANA Logistics','SAP S/4HANA Manufacturing','SAP S/4HANA Cloud','SAP S/4HANA On Premise','SAP Activate','SAP Migration Cockpit','CDS Views','Core Data Services','SAP BTP','Business Technology Platform','SAP Integration Suite','SAP API Management','SAP Cloud Connector','SAP Gateway','OData Services','SAP BRFplus','SAP Analytics Cloud','SAP S/4HANA Embedded Analytics','SAP S/4HANA Implementation','S/4HANA Conversion','S/4HANA Greenfield','S/4HANA Brownfield','SAP Fiori Consultant','SAP S/4HANA Functional Consultant','SAP S/4HANA Technical Consultant','SAP ABAP on HANA']),
    ('3ebd65ac-87cc-4bf3-91fe-7413ebd096da', v_salesforce_id, 'Commerce Cloud', ARRAY['Commerce Cloud','Demandware','Salesforce Commerce Cloud','SFCC','Salesforce B2C Commerce','Salesforce B2B Commerce','B2B Commerce Cloud','Salesforce Digital Storefront','Commerce Cloud Einstein','Commerce Cloud API','OCAPI','Salesforce Commerce API','SFRA','Storefront Reference Architecture','ISML','Demandware Script','SiteGenesis','Custom Controller','Salesforce OMS','Order Management System','Commerce Cloud Integration','Salesforce Commerce Cloud Developer','Commerce Cloud Technical Consultant','Commerce Cloud Implementation','B2C Storefront Developer','Salesforce Commerce Cloud Architect']),
    ('44712e32-3693-4c52-b87e-e0bb0c6dde41', v_workday_id, 'Workday Financial & HCM', ARRAY['Workday Financials','Workday HCM','Workday Human Capital Management','Workday Cloud','Workday Platform','Workday SaaS','Workday Tenant','Workday Instance','Workday Application','Workday Implementation','Core HCM','Workday Financial Management','Workday Studio','Workday Integration','Workday EIB','Enterprise Interface Builder','Workday Core Connector','Workday Web Services','Workday SOAP API','Workday REST API','Workday Report-as-a-Service','Workday Web Service Call','Workday XSLT','Workday XPath','Workday Custom Integration','Workday Document Transformation','Workday Cloud Platform','WCP','Workday Extend','Workday Integration System User','Workday Connector','Workday Workday-to-Workday Integration','Workday Prism Integration','Workday to SAP Integration','Workday to Oracle Integration','Workday to ADP','Workday to Salesforce','Workday to ServiceNow','Workday to Azure AD','Workday to Okta','Workday to Microsoft 365','Workday Web Services Integration','Workday EIB Integration','Workday Cloud Connect','Workday Connector for Benefits','Workday Connector for Payroll','Workday Integration Cloud','Workday Studio IDE','Workday Object Model','WQL','Workday Query Language']),
    ('5528269a-b858-4640-8f7c-1930dcb9bff0', v_microsoft_id, 'Microsoft 365', ARRAY['Office 365','M365','Microsoft 365','O365','Microsoft Cloud','Microsoft 365 Admin','Microsoft 365 Tenant','Microsoft 365 Portal','Microsoft 365 Subscription','Microsoft 365 Enterprise','Microsoft 365 Business','Microsoft 365 Apps','Microsoft 365 Defender','Microsoft 365 Compliance','Microsoft 365 Security','Microsoft 365 E3','Microsoft 365 E5','Microsoft 365 Admin Center','Exchange Admin Center','SharePoint Admin Center','Teams Admin Center','Security & Compliance Admin Center','Microsoft Graph API','PowerShell M365','PowerShell Exchange Online','PowerShell SharePoint Online','PowerShell Teams','PowerShell Intune','Azure AD Connect','Modern Authentication','Service Health Dashboard','Microsoft 365 Administrator','M365 Engineer','Office 365 Engineer','Exchange Administrator','Teams Administrator','SharePoint Administrator','Intune Administrator','Power Platform Developer','M365 Support Specialist','Modern Workplace Engineer']),
    ('676a0230-beff-4762-9af1-437320820799', v_qlik_id, 'Qlik Sense & Qlikview', ARRAY['QlikSense','Qlik Sense','QlikView','Qlik View','Qlik Cloud','Qlik SaaS','Qlik Sense Enterprise','Qlik Sense Desktop','Qlik Sense Server','QlikView Desktop','QlikView Server','Qlik NPrinting','Qlik GeoAnalytics','Qlik Alerting','Qlik Insight Bot','Qlik Data Catalyst','Qlik Compose','Qlik Replicate','Qlik Script','Qlik Load Script','Qlik Data Model','Data Model Viewer','Data Load Editor','Data Manager','QVD','QVW','QVF','QVD Files','QVD Generator','Qlik REST Connector','Qlik Web Connector','Qlik Salesforce Connector','Qlik SAP Connector','Qlik Insight Advisor','Qlik Mashup','Qlik Engine API','Qlik Sense API','QRS API','Qlik Dev Hub','Qlik Repository Service','Qlik Proxy Service','Qlik Engine Service','Qlik Scheduler Service','Qlik Management Console','QMC','Qlik Sense Hub','Qlik Sense Proxy','Qlik Automation','Qlik Application Automation','Qlik Cloud Data Services','Qlik Data Integration','Qlik NPrinting Reports','Qlik NPrinting Designer','Qlik NPrinting Server','Qlik NPrinting Scheduler']),
    ('6ab382bb-c63a-4ae5-bf4e-8af943a684dc', v_oracle_id, 'Oracle ERP Cloud', ARRAY['Oracle ERP','Oracle Fusion','Oracle Cloud ERP','Oracle ERP Cloud','Oracle Fusion ERP','Oracle Fusion Applications','Oracle Cloud Financials','Oracle Cloud Procurement','Oracle Cloud Projects','Oracle Cloud SCM','Oracle Cloud Supply Chain','Oracle Cloud Manufacturing','Oracle Cloud PPM','Oracle Cloud EPM','Oracle Fusion Financials','Oracle Fusion SCM','Oracle Fusion Procurement','Oracle Fusion PPM','Oracle Fusion Projects','Oracle Fusion Middleware']),
    ('6ee31178-dc77-46de-a307-de482202e605', v_microsoft_id, 'Power BI', ARRAY['Microsoft Power BI','Power BI','Power BI Service','Power BI Desktop','Power BI Pro','Power BI Premium','Power BI Embedded','Power BI Report Server','Power BI Gateway','On-premises Data Gateway','Power BI Mobile','Power BI Compliance']),
    ('7e1d6655-1a29-4200-863c-a602db6f7912', v_salesforce_id, 'Sales Cloud', ARRAY['Salesforce','SFDC','Sales Cloud','Salesforce Sales Cloud','Salesforce CRM','CRM Cloud','Products and Price Books','CPQ','Salesforce Inbox','Einstein Activity Capture','Lightning Experience','Salesforce Lightning','Lightning App Builder','Lightning Components','Visualforce','SOQL','Salesforce Admin','Salesforce Developer','Salesforce Functional Consultant','Salesforce Architect']),
    ('851f348c-8568-421d-aa6a-cf066d280cd4', v_google_id, 'Google Cloud Platform', ARRAY['GCP','Google Cloud','Google Kubernetes Engine','GKE','Cloud Run','Google Cloud Platform','Cloud SQL','Vertex AI','Eventarc','Cloud IAM','CIAM','GCLOUD','App Engine','Cloud Functions','Compute Engine','Anthos']),
    ('86283e20-2f39-4814-a874-b58094035c41', v_sap_id, 'SAP Business One', ARRAY['SAP B1','Business One','SAP Business One','SAP B1 HANA','SAP B1 SQL','SAP Business One HANA','SAP Business One SQL','SAP B1 SDK','SAP Business One Integration Framework','B1iF','B1 Integration Hub','SAP Business One Studio','SAP Crystal Reports','SAP B1 Add-ons','B1 Usability Package','Boyum','SAP B1 Service Layer','SAP B1 DI API','SAP B1 DI Server','SAP B1 Queries','SAP B1 UI API','SAP Business One Mobile','SAP Business One Cloud','SAP Business One Implementation','SAP B1 Functional Consultant','SAP B1 Technical Consultant','SAP B1 Developer','SAP Business One Administrator']),
    ('8bd23d6c-7c48-4cc2-90bf-0ab52156cd73', v_microsoft_id, 'Dynamics 365 CRM', ARRAY['Dynamics 365 Sales','Dynamics 365 Customer Service','Dynamics 365 Field Service','MB-210','MB-220','MB-230','MB-240','Microsoft Dynamics','Microsoft Dynamics 365','Dynamics CRM','Dynamics 365 CRM','Dynamics 365 CE','Dynamics Customer Engagement','Dynamics 365 Online','Dynamics 365 On-Premise','Dynamics 365 Marketing','Dynamics 365 Project Service','Dynamics 365 Business Central']),
    ('8f945f62-0896-403c-a870-db2288b17ac0', v_zoho_id, 'Zoho Marketing', ARRAY['ZOHO CAMPAIGNS','ZOHO MARKETING','ZOHO SOCIAL','ZOHO FORMS','ZOHO PAGESENSE','ZOHO SURVEY','ZOHO SALESIQ','ZOHO BACKSTAGE']),
    ('8fabcedf-2e0c-4967-bd33-f8ae9120e213', v_salesforce_id, 'Marketing Cloud', ARRAY['Marketing Cloud','Salesforce Marketing','Salesforce Marketing Cloud','SFMC','ExactTarget','Mobile Studio','Advertising Studio','Social Studio','Interaction Studio','Datorama','Query Studio','AMPscript','DESelect','CloudPages','Einstein Engagement','Marketing Cloud Connect','MCC','Marketing Cloud API','Marketing Cloud Admin','Marketing Cloud Consultant','Salesforce Marketing Cloud Developer','SFMC Developer','SFMC Technical Consultant','Salesforce Marketing Architect']),
    ('a453ba33-0f27-49bf-b1c7-e18c5fdc41cb', v_microsoft_id, 'Dynamics 365 ERP', ARRAY['Dynamics 365','D365','Dynamics 365 Finance','Dynamics 365 Supply Chain Management','Dynamics 365 Commerce','Dynamics 365 Human Resources','Dynamics 365 Project Operations','D365 F&O','D365 Finance','D365 SCM','D365 BC']),
    ('ab0b7bd2-2700-4d22-b86e-616ca8a2237f', v_zoho_id, 'Zoho Desk', ARRAY['ZOHO ASSIST','ZOHO LENS']),
    ('b87bdc13-ad0a-4a0b-97ee-81014a67d17c', v_oracle_id, 'Oracle HCM Cloud', ARRAY['Oracle HCM','Oracle Human Capital','Fusion HCM','Oracle Human Capital Management','Oracle HR Cloud','HCM Cloud','Oracle HCM SaaS','Oracle HCM Suite','Oracle Workforce Cloud','OTBI','Oracle Transactional Business Intelligence','Oracle Analytics Cloud','OAC','FSM','HCM Extracts','Oracle Payroll Cloud','Oracle Recruiting Cloud','Oracle Learning Cloud','Oracle HRIS Analyst','Oracle HR Cloud Analyst','Oracle Cloud HCM']),
    ('bb375448-50d0-4905-9c3e-699c091792d2', v_salesforce_id, 'Service Cloud', ARRAY['Service Cloud','Salesforce Service','Salesforce Service Cloud','Einstein Bots','Service Cloud Voice','CTI Integration','Field Service Lightning','FSL','Field Service Mobile','OmniStudio','Salesforce Digital Engagement','Service Cloud Admin','Service Cloud Developer','Salesforce Support Engineer','Salesforce Technical Consultant']),
    ('c0120baa-b908-4cb0-bf25-35f17dbd34be', v_sap_id, 'SAP Ariba', ARRAY['Ariba','AP Ariba','Ariba Network','Ariba Cloud','Ariba Procurement','Ariba Sourcing','Ariba Contracts','Ariba Contract Management','Ariba Buying','Ariba Buying and Invoicing','Ariba Supplier Management','Ariba Supplier Lifecycle','Ariba Supplier Risk','Ariba Catalog','Ariba Commerce Automation','Ariba Spend Visibility','Ariba Integration Toolkit','Ariba API','Ariba Procurement Cloud','Ariba Administration','Ariba Configuration','Ariba Implementation','Ariba Consultant','Ariba Functional Consultant','Ariba Technical Consultant','Ariba Integration','Ariba CIG','Cloud Integration Gateway','SAP Ariba Connect','SAP Business Network','Ariba Upstream','Ariba Downstream']),
    ('d8723e1e-0610-4dc5-bebb-57fdaf8bd233', v_google_id, 'Google Workspace', ARRAY['G Suite','Google Apps','Google Workspace','Google Admin','Google Cloud Identity','Google Admin Console','Workspace Admin','Workspace Domain','Google Workspace Enterprise','Google Workspace Business','Workspace Essentials','Workspace for Education','Workspace API','Google Vault','eDiscovery','Google Workspace API']),
    ('da1f6641-4aca-434e-ab1d-b6b3e0fb57ee', v_sap_id, 'SAP ERP', ARRAY['SAP ERP','SAP ECC','SAP R/3','SAP R3','SAP ERP Central Component','SAP ERP 6.0','SAP NetWeaver','SAP GUI','SAP Modules','SAP FI','SAP CO','SAP MM','SAP SD','SAP PP','SAP PM','SAP QM','SAP HR','SAP HCM','SAP PS','SAP Basis','SAP ABAP','ABAP Developer','SAP Workflow','SAP SmartForms','SAP IDoc','LSMW','BAPI','BADI','User Exit','Enhancement Point','SAP Data Migration','SAP Functional Consultant','SAP Technical Consultant','SAP ERP Implementation','SAP ERP Customization','SAP ERP Support']),
    ('e1da0642-de7a-454b-b89e-e4e6be4ee685', v_amazon_id, 'AWS', ARRAY['Amazon Web Services','AWS','AWS Cloud','AWS Console','AWS Account','AWS CLI','AWS SDK','AWS CloudShell','AWS Management Console','AWS Marketplace','AWS Free Tier','AWS Organizations','AWS Control Tower','AWS Landing Zone','AWS Well-Architected','AWS EC2','Elastic Compute Cloud','EC2 Auto Scaling','Launch Template','AMI','EBS','Elastic Block Store','Instance Profile','ECS','Elastic Container Service','Fargate','EKS','Elastic Kubernetes Service','ECR','Elastic Container Registry','Lambda','AWS Batch','AWS Lightsail','Elastic Beanstalk','AWS Outposts','AWS Wavelength','AWS Graviton','Route 53','Global Accelerator','AWS Cloud WAN','Simple Storage Service','Glacier','Glacier Deep Archive','S3 Lifecycle Policy','Elastic File System','FSx','FSx for Windows','FSx for Lustre','Relational Database Service','Aurora','MySQL on RDS','PostgreSQL on RDS','MariaDB on RDS','SQL Server RDS','DynamoDB','NoSQL Database','ElastiCache','Redis','Memcached','Redshift','CodeCommit','CodeBuild','CodeDeploy','CodePipeline','AWS CloudFormation','CloudFormation Template','CDK','AWS CDK','AWS SAM','OpsWorks','CodeArtifact','AWS Developer Tools','AWS Systems Manager','CloudWatch','CloudWatch Logs','CloudWatch Metrics','CloudWatch Dashboards','CloudWatch Alarms','CloudTrail','X-Ray','AWS Config','AWS Health Dashboard','AWS Trusted Advisor','CloudWatch Agent','AWS Logs Insights','CloudWatch Events','EventBridge','AWS Systems Manager OpsCenter','AWS Application Insights','SNS','Simple Notification Service','SQS','Simple Queue Service','Step Functions','AWS AppFlow','AWS DataSync','AWS Glue','AWS Transfer Family','AWS MGN','AWS Migration Hub','AWS Integration','AWS Service Catalog','SageMaker','SageMaker Studio','SageMaker Notebook','Rekognition','Polly','Transcribe','Translate','Comprehend','Kendra','Lex','Textract','Forecast','Personalize','AWS DeepRacer','AWS DeepLens','AWS DeepComposer','AWS IoT Core','AWS IoT Greengrass','AWS IoT Device Management','AWS IoT Analytics','AWS IoT SiteWise','AWS IoT Events','AWS IoT Things Graph','AWS IoT 1-Click','AWS Partner Network','APN','AWS Certified','AWS Solutions Architect','AWS DevOps Engineer','AWS SysOps Administrator','AWS Developer','AWS Data Analytics','AWS Machine Learning','AWS Security','AWS Advanced Networking','AWS Database']),
    ('e65c5fa0-3b96-4501-9c7c-e57293ad1cc9', v_oracle_id, 'Oracle Forms', ARRAY['Oracle Forms','Oracle Forms & Reports','Oracle Reports','Oracle Forms and Reports','Oracle Forms y Reports','Reportes de Oracle','Oracle Forms Developer','Oracle Forms Builder','Oracle Reports Builder','Oracle Developer Suite','Oracle Forms Runtime','Oracle Forms Services','Oracle Reports Server','Oracle Forms 6i','Oracle Forms 10g','Oracle Forms 11g','Oracle Forms 12c','Oracle Reports 6i','Oracle Reports 10g','Oracle Reports 11g','Oracle Reports 12c','Oracle WebLogic Server','Oracle Application Server','OC4J','Forms Servlet','Reports Servlet','rwservlet','WebUtil','EBS Forms Personalization','EBS Custom Forms','Oracle Forms Migration','Forms Upgrade','Reports Deployment','Forms Listener Servlet','RWServer','Forms Configuration','Oracle Reports Runtime','Report Server','RDF File','REP File','Report Builder Layout','Report Data Model','PL/SQL Report Trigger','Before Report','After Report','Format Trigger','Report Parameter Form','RDF to PDF']),
    ('fa7bbf29-3ea2-4eca-b6a5-f3b31fc66d5c', v_servicenow_id, 'ServiceNow ITSM', ARRAY['ServiceNow','SNOW','ServiceNow ITSM','ServiceNow Platform','Now Platform','ServiceNow Cloud','ServiceNow SaaS','GlideRecord','GlideAjax','GlideForm','GlideSystem','ServiceNow Studio','ServiceNow CSM','ServiceNow HRSD','ServiceNow SecOps','ServiceNow ITOM','ServiceNow ITBM','ServiceNow GRC','ServiceNow IRM','ServiceNow App Engine','App Engine Studio','Now Experience UI Framework','ServiceNow Mobile App','ServiceNow Mobile Studio']),
    ('faca10c9-6bd2-43af-93ce-5290751d9855', v_oracle_id, 'Oracle Database', ARRAY['Oracle DB','Oracle 19c','Oracle 21c','Oracle Database','Oracle 11g','Oracle 12c','Oracle 18c','Oracle SQL','Oracle PL/SQL','Oracle Cloud Database','Oracle Autonomous Database','Oracle Database Appliance','Oracle XE','Oracle RAC','Oracle ASM','Oracle DBA','Real Application Clusters','Automatic Storage Management','Data Guard','GoldenGate','RMAN','Recovery Manager','Oracle Backup','Oracle Restore','Oracle Grid Infrastructure','Oracle Enterprise Manager','OEM','Oracle Listener','tnsnames.ora','sqlnet.ora','Oracle Service Name','Oracle Instance','Oracle Tablespace','Redo Logs','Undo Tablespace','Control Files','Archive Logs','PL/SQL Developer','Oracle SQL Developer','PL/SQL','Oracle Data Guard','Active Data Guard','Oracle GoldenGate','RMAN Backup','Flashback Database','Flashback Query','Standby Database','Oracle Cloud Infrastructure','OCI','Oracle ATP','Oracle ADW','Oracle Exadata','Oracle Data Safe','Oracle Integration Cloud','OIC','Oracle SQL Developer Web','Oracle REST Data Services','ORDS','Toad for Oracle'])
    ON CONFLICT (id) DO UPDATE SET
        vendor_id = EXCLUDED.vendor_id,
        name = EXCLUDED.name,
        keywords = EXCLUDED.keywords;
END $$;
